server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_shema: public
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    drop-first: false
app:
  connection:
    userAgent: MyLearningSearchingBot/1.2 (archibaldas.shtml.com)
    chromeUserAgents:
      - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
      - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
      - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
    referer: https://www.google.com
    timeout: 300000

  lemma-finder:
    particle-types:
      - "МЕЖД"
      - "ПРЕДЛ"
      - "СОЮЗ"
      - "МС"
      - "МС-П"


  cache:
    remove_time: 5000

indexing-settings:
  sites:
    - url: http://www.playback.ru
      name: PlayBack
    - url: https://ipfran.ru
      name: ИПФ РАН
    - url: https://nikoartgallery.com/
      name: NikoArt
    - url: https://www.svetlovka.ru
      name: Svetlovka
    - url: https://www.lutherancathedral.ru/
      name: LutheranCathedral

logging:
  level:
    searchengine: INFO

